---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markus.
--- DateTime: 2/16/19 11:47 PM
---


local WirebaitLib = {}

---- [[Dissector Modules]] ----
--WirebaitLib.DissectorRunner = require("dissector.DissectorRunner");
--WirebaitLib.DissectorTable  = require("dissector.DissectorTable");

---- [[Packet Data Modules]] ----
--TODO

---- [[Packet Info Modules]] ----
--TODO

---- [[Primitives Modules]] ----
--TODO


local ProtoField = require("wirebaitlib.dissector.ProtoField");

local WirebaitLib = {
    UInt64           = require("wirebaitlib.primitives.UInt64"),
    Int64            = require("wirebaitlib.primitives.Int64"),
    Proto            = require("wirebaitlib.dissector.Proto"),
    ProtoField       = ProtoField,
    base             = ProtoField.base,
    treeitem         = require("wirebaitlib.dissector.TreeItem"),
    Tvb              = require("wirebaitlib.packet_data.Tvb"),
    TvbRange         = require("wirebaitlib.packet_data.TvbRange"),
    packet           = require("wirebaitlib.packet_data.Packet"),
    --FieldInfo        = require("wirebaitlib.packet_info."),
    --Field            = require("wirebaitlib.packet_info."),
    pcap_reader      = require("wirebaitlib.packet_data.PcapReader"),
    dissector_runner = require("wirebaitlib.dissector.DissectorRunner"),

    state = { --[[ state to keep track of the dissector wirebait is testing ]]
        dissector_filepath = nil,
        proto = nil,
        packet_info = { --TODO should be reset after each packet
            cols={},
            treeitems_array = {} --treeitems are added to that array so they can be displayed after the whole packet is dissected
        },
        dissector_table = {
            udp = { port = nil },
            tcp = { port = nil }
        },
        --field_extractors = {} --used to keep track of field extractors (i.e. wirebait.Field.new())
    }-------------------end of wirebait.state --------------
}

return WirebaitLib;