---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markus.
--- DateTime: 2/18/19 4:03 PM
---

--[[
    WireBait for wirebait is a lua package to help write Wireshark
    Dissectors in lua
    [Wirebait on Github](https://github.com/MarkoPaul0/WireBait)
    Copyright (C) 2015-2017 Markus Leballeux

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
]]

local is_standalone_test = not tester; --if only this file is being tested (not part of run all)
local tester = tester or require("tests.tester")

local TvbRange  = require("wirebaitlib.packet_data.TvbRange");
local ByteArray = require("wirebaitlib.primitives.ByteArray");

--[[ All variables here need to be kept local, however the unit test framework will run
each individual test function added with UnitTestsSet:addTest() in its own environment,
therefore forgetting the local keyword will not have a negative impact.
]]--
--Creating unit tests
local unit_tests = tester.newUnitTestsSet("TvbRange Unit Tests");

unit_tests:addTest("Testing TvbRange construction", function()
    local b = ByteArray.new("A0102FB1");
    local tvb_range = TvbRange.new(b);
    tester.assert(tvb_range.m_data, b, "Wrong underlying data");
    tester.assert(tvb_range:len(), 4, "Wrong size after construction")
end);

unit_tests:addTest("Testing TvbRange:len()", function()
    tester.assert(TvbRange.new(ByteArray.new("4845")):len(), 2, "Wrong byte length");
end)

unit_tests:addTest("Testing wirebait buffer:uint() (Big-Endian)", function()
    tester.assert(TvbRange.new(ByteArray.new("48454C4C")):uint(), 1212501068);
end)

unit_tests:addTest("Testing wirebait buffer:uint64() (Big-Endian)", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("6D45D89F55C23601")):uint64()), "7873937702377371137");
end)

unit_tests:addTest("Testing wirebait buffer:uint64() (Big-Endian) Largest uint64", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFFFF")):uint64()), "18446744073709551615");
end)

unit_tests:addTest("Testing wirebait buffer:le_uint64() (Little-Endian) Largest uint64", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFFFF")):le_uint64()), "18446744073709551615");
end)

unit_tests:addTest("Testing wirebait buffer:le_uint() (Little-Endian)", function()
    tester.assert(TvbRange.new(ByteArray.new("48454C4C")):le_uint(), 1280066888);
end)

unit_tests:addTest("Testing wirebait buffer:le_uint64() (Little-Endian)", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("48454C4C28520000")):le_uint64()), "90333032236360");
end)

unit_tests:addTest("Testing wirebait buffer:int() (Big-Endian) Negative Number", function()
    tester.assert(TvbRange.new(ByteArray.new("FFFF2852")):int(), -55214);
end)

unit_tests:addTest("Testing wirebait buffer:int() (Big-Endian) Zero", function()
    tester.assert(TvbRange.new(ByteArray.new("00000000")):int(), 0);
end)

unit_tests:addTest("Testing wirebait buffer:int() (Big-Endian) -1", function()
    tester.assert(TvbRange.new(ByteArray.new("FFFFFFFF")):int(), -1);
end)

unit_tests:addTest("Testing wirebait buffer:int() (Big-Endian) Largest Negative Number", function()
    tester.assert(TvbRange.new(ByteArray.new("80000000")):int(), -2147483648);
end)

unit_tests:addTest("Testing wirebait buffer:int() (Big-Endian) Largest Positive Number", function()
    tester.assert(TvbRange.new(ByteArray.new("7FFFFFFF")):int(), 2147483647);
end)

unit_tests:addTest("Testing wirebait buffer:int64() (Big-Endian) Zero", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("0000000000000000")):int64()), "0");
end)

unit_tests:addTest("Testing wirebait buffer:int64() (Big-Endian) -1", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFFFF")):int64()), "-1");
end)

unit_tests:addTest("Testing wirebait buffer:int64() (Big-Endian) Large Negative Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("EFFFFFFFFFFFFFFF")):int64()), "-1152921504606846977");
end)

unit_tests:addTest("Testing wirebait buffer:int64() (Big-Endian) Largest Negative Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("8000000000000000")):int64()), "-9223372036854775808");
end)

unit_tests:addTest("Testing wirebait buffer:int64() (Big-Endian) Large Positive Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("7FFFFFFFFFFFFFFF")):int64()), "9223372036854775807");
end)

unit_tests:addTest("Testing wirebait buffer:le_int() (Little-Endian) Negative Number", function()
    tester.assert(TvbRange.new(ByteArray.new("5228FFFF")):le_int(), -55214);
end)

unit_tests:addTest("Testing wirebait buffer:le_int() (Little-Endian) Zero", function()
    tester.assert(TvbRange.new(ByteArray.new("00000000")):le_int(), 0);
end)

unit_tests:addTest("Testing wirebait buffer:le_int() (Little-Endian) -1", function()
    tester.assert(TvbRange.new(ByteArray.new("FFFFFFFF")):le_int(), -1);
end)

unit_tests:addTest("Testing wirebait buffer:le_int() (Little-Endian) Largest Negative Number", function()
    tester.assert(TvbRange.new(ByteArray.new("00000080")):le_int(), -2147483648);
end)

unit_tests:addTest("Testing wirebait buffer:le_int() (Little-Endian) Largest Positive Number", function()
    tester.assert(TvbRange.new(ByteArray.new("FFFFFF7F")):le_int(), 2147483647);
end)

unit_tests:addTest("Testing wirebait buffer:le_int64() (Little-Endian) Zero", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("0000000000000000")):le_int64()), "0");
end)

unit_tests:addTest("Testing wirebait buffer:le_int64() (Little-Endian) -1", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFFFF")):le_int64()), "-1");
end)

unit_tests:addTest("Testing wirebait buffer:le_int64() (Little-Endian) Large Negative Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFFEF")):le_int64()), "-1152921504606846977");
end)

unit_tests:addTest("Testing wirebait buffer:le_int64() (Little-Endian) Largest Negative Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("0000000000000080")):le_int64()), "-9223372036854775808");
end)

unit_tests:addTest("Testing wirebait buffer:le_int64() (Little-Endian) Large Positive Number", function()
    tester.assert(tostring(TvbRange.new(ByteArray.new("FFFFFFFFFFFFFF7F")):le_int64()), "9223372036854775807");
end)

if is_standalone_test then
    tester.test(unit_tests);
    tester.printReport();
else
    return unit_tests
end
