---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markus.
--- DateTime: 2/15/19 11:39 PM
---

function DissectorTable.new()
    dissector_table = {
        udp = { port = {} },
        tcp = { port = {} },
    }

    local function newPortTable()
        port_table = {}

        function port_table:add(port, proto_handle)
            assert(port and proto_handle, "port and proto_handle cannot be nil!");
            local port_number = tonumber(port);
            assert(port_number >= 0 and port_number <= 65535, "A port must be between 0 and 65535!")
            self[port_number] = proto_handle;
        end

        return port_table;
    end

    dissector_table.udp.port = newPortTable();
    dissector_table.tcp.port = newPortTable();

    function dissector_table.get(path)
        local obj = dissector_table;
        path:gsub("%a+", function(split_path) obj = obj[split_path] end)
        return obj;
    end

    return dissector_table;
end