---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markus.
--- DateTime: 2/15/19 11:42 PM
---

--[[ Equivalent of [wireshark Proto](https://wiki.wireshark.org/LuaAPI/Proto#Proto) ]]
function Proto.new(abbr, description)
    assert(description and abbr, "Proto argument should not be nil!")
    local proto = {
        _struct_type = "Proto";
        m_description = description,
        m_abbr = abbr,
        fields = {}, --protofields
        dissector = {}, --dissection function
        name = description --ws api
    }

    assert(state.proto == nil, "Wirebait currenlty only support 1 proto per dissector file!");
    state.proto = proto;
    return proto;
end