---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by markus.
--- DateTime: 2/16/19 12:18 PM
---


--TODO: create a byte array class to encapsulate basic HEX strings and use it in PcapReader and in Tvb

local ByteArray = {};

function ByteArray.new()
    assert(false, "ByteArray not available yet")
    local byte_array = {};
end

return ByteArray;